@startuml

skinparam classAttributeIconSize 0

package util <<Folder>> {
    interface Observer {
    +update(observable: Observable)
    }
    abstract Observable {
    +addObserver(observer: Observer)
    +deleteObserver(observer: Observer)
    +notifyObserver()
    }
}
Observable o-right-> Observer

class Coche {
-encoder : Encoder
-printHub : PrintHub
-menuList[] : List<Menu>
+print(text)
}
Coche o--> PrintHub
Coche --> Menu
Coche --> Encoder

class Console {
+print(text) - Print by Console
}
Console ..|> PrintHub

class Coolant {
-coolOBD
+update()
+print()
}
Coolant --|> ECU

interface ECU {
+print() : String
+update()
}
ECU ..|> Observer

class Encoder {
Encoder(e1, e2, eb) : Encoder
getValue() : int
getButtonValue() : bool
}

class Gas {
-instMPG
-mpg
-mpgSamples
-commands{} : OBDResponse
-file : File
-calculateGas()
+print()
+update()
}
Gas --|> ECU
Gas --> File

class LCD {
LCD(rs, en, d4, d5, d6, d7) : LCD
writeMessage(message : String)
clearDisplay()
moveCursor(cursor, direction, times)
display(display, cursor, blink)
home()
writeRAM()
}

class LCDSingle {
-lcd : LCD
+print(text) - Print by LCD
}
LCDSingle ..|> PrintHub
LCDSingle --|> LCD

class Menu {
-ecuList[2] : List<ECU>
+print() : String[] ECU class
}
Menu o--> ECU

class OBD {

OBD(port, fast, timeout) : OBD
query(obd.commands.{}).value.magnitude : String
close()
}

class OBDSingle {
-obd : OBD
}
OBDSingle --|> Observable
OBDSingle --|> OBD

interface PrintHub {
+print(text)
}

abstract RPM {
-rpmOBD
+update()
#print()
}
RPM --|> ECU

class RPMNumber {
+print()
}
RPMNumber --|> RPM

class RPMGraph {

+print()
}
RPMGraph --|> RPM

class File {
-FILENAME
+saveFile(commands[])
-openFile() : commands[]
}

class TimeTurbo {
-speedOBD
-coolOBD
-time : Duration
-calculateTime()
+print()
+update()
}
TimeTurbo --|> ECU



note "External Library" as Lib
Lib .. LCD
Lib .. OBD
Lib .. Encoder

note "Clase main" as Main
Main .. Coche

note "This is Singleton" as Singleton
Singleton .. OBDSingle
Singleton .. LCDSingle












@enduml