@startuml

skinparam classAttributeIconSize 0

package util <<Folder>> {
    interface Observer {
    +update(observable: Observable)
    }

    abstract Observable {
    +attach(observer: Observer)
    +detach(observer: Observer)
    +notify()
    }
    Observable o-right-> Observer
}

package interfaces <<Folder>> {
    class Console {
    +print(text) - Print by Console
    }

    class LCDSingle {
    -lcd : LCD
    +print(text) - Print by LCD
    }

    interface PrintHub {
    +print(text)
    }
}

package external_libraries <<Folder>> {
    class Encoder {
    Encoder(e1, e2, eb) : Encoder
    getValue() : int
    getButtonValue() : bool
    }

    class LCD {
    LCD(rs, en, d4, d5, d6, d7) : LCD
    writeMessage(message : String)
    clearDisplay()
    moveCursor(cursor, direction, times)
    display(display, cursor, blink)
    home()
    writeRAM()
    }

    class OBD {
    OBD(port, fast, timeout) : OBD
    query(obd.commands.{}).value.magnitude : String
    close()
    }
}

class Car {
+stoichiometric : int
+density : int
-encoder : Encoder
-printHub : PrintHub
-menuList : List<Menu>
+mainLoop()
+dieselCar()
}

class Coolant {
-coolOBD
+update()
+print()
}

interface ECU {
+print() : String
+update()
}

class Gas {
-instMPG
-mpg
-mpgSamples
-commands{} : OBDResponse
-file : File
-calculateGas()
+print()
+update()
}

class Menu {
-ecuList[2] : List<ECU>
+print() : String[] ECU class
}

class OBDSingle {
-obd : OBD
-printer : PrintHub
-observers : List<Observer>
-commands : Dictionary<String>
-exit : Bool
-connection()
-getParams()
-tick()
+destroy()
+getCommands()
}

abstract RPM {
-rpm : float
+update()
#print()
}

class RPMNumber {
+print()
}

class RPMGraph {
-rpmSegments : int
+print()
}

class File {
-FILENAME
+saveFile(commands[])
-openFile() : commands[]
}

class TimeTurbo {
-speedOBD
-coolOBD
-time : Duration
-calculateTime()
+print()
+update()
}


Car o--> PrintHub
Car --> Menu
Car --> Encoder
Coolant --|> ECU
Console ..|> PrintHub
ECU ..|> Observer
LCDSingle ..|> PrintHub
LCDSingle --|> LCD
Gas --|> ECU
Gas --> File
Menu o--> ECU
OBDSingle --|> Observable
OBDSingle --|> OBD
RPM --|> ECU
RPMNumber --|> RPM
RPMGraph --|> RPM
TimeTurbo --|> ECU


note "Clase main" as Main
Main .. Coche

note "This is Singleton" as Singleton
Singleton .. OBDSingle
Singleton .. LCDSingle












@enduml